apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-kube
  namespace: machinelearning
spec:
  containers:
  - name: simple-container
    image: nginx
    resources:
      limits:
        cpu: "750m"
        memory: "500Mi"